# Generated by Django 5.0.4 on 2024-04-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doct', '0003_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Sign',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
