# Generated by Django 5.0.4 on 2024-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doct', '0005_alter_sign_options_alter_sign_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sign',
            options={},
        ),
        migrations.AlterModelManagers(
            name='sign',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='sign',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sign',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
